---
- name: Install Docker on Fedora
  hosts: all
  become: true
  vars:
    docker_repo_url: https://download.docker.com/linux/fedora/docker-ce.repo
    docker_gpg_key: https://download.docker.com/linux/fedora/gpg

  tasks:
    - name: Ensure dnf-plugins-core is installed
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      tags: install

    - name: Add Docker repository (if not already added)
      ansible.builtin.command: dnf config-manager --add-repo {{ docker_repo_url }}
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
      tags: repo

    - name: Import Docker GPG key
      ansible.builtin.rpm_key:
        key: "{{ docker_gpg_key }}"
        state: present
      tags: repo

    - name: Install Docker and related packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      tags: install

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      tags: service

    - name: Display Docker version
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false
      tags: validate

    - name: Print Docker version
      ansible.builtin.debug:
        var: docker_version.stdout
      tags: validate

    - name: Validate Docker installation by running docker ps
      ansible.builtin.command: docker ps
      register: docker_status
      changed_when: false
      failed_when: docker_status.rc != 0
      tags: validate

    - name: Print Docker validation result
      ansible.builtin.debug:
        var: docker_status.stdout
      tags: validate

  handlers:
    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
