image: registry.fedoraproject.org/fedora:latest

stages:
  - lint
  - syntax-check
  - dry-run

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

before_script:
  - dnf install -y python3-pip git
  - pip3 install ansible ansible-lint
  - mkdir -p inventories
  - echo "[local]" > inventories/test
  - echo "localhost ansible_connection=local" >> inventories/test

lint:
  stage: lint
  script:
    - ansible-lint playbooks/**/*.yml
    - ansible-lint roles/config_motd/tasks/*.yml

syntax-check:
  stage: syntax-check
  script:
    - |
      for pb in playbooks/**/*.yml; do
        echo "🔍 Checking syntax for $pb"
        ansible-playbook -i inventories/test "$pb" --syntax-check
      done

dry-run:
  stage: dry-run
  script:
    - |
      for pb in playbooks/**/*.yml; do
        echo "🧪 Dry-run: $pb"
        ansible-playbook -i inventories/test "$pb" --check --diff
      done
