PidFile=/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server=10.0.0.91
ListenPort=10050
ListenIP=0.0.0.0
ServerActive=10.0.0.91
Hostname=centaurus.internal.das
Include=/etc/zabbix/zabbix_agentd.d/*.conf
