# roles/deploy_git_repo/meta/main.yml
---
galaxy_info:
  role_name: deploy_git_repo
  author: Rajesh Prashanth Anandavadivel
  description: Clone and deploy a Git repository to a specified directory.
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
        - 9

dependencies: []
