# roles/config_ps1/meta/main.yml
---
galaxy_info:
  role_name: config_ps1
  author: Rajesh Prashanth Anandavadivel
  description: Configure a custom PS1 shell prompt for all users via /etc/profile.d.
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
        - 9

dependencies: []
