---
- name: Check CPU Utilization
  hosts: "{{ target | default('all') }}"
  gather_facts: false

  tasks:
    - name: Get CPU usage from top command
      ansible.builtin.command:
        cmd: "top -bn1 | grep 'Cpu(s)'"
      register: cpu_usage
      changed_when: false

    - name: Display CPU usage
      ansible.builtin.debug:
        msg: "{{ cpu_usage.stdout }}"
