---
- name: Restore specific Docker volume from backup
  hosts: "{{ target | default('all') }}"
  become: true
  gather_facts: false

  vars:
    backup_base_dir: /opt/homelab/backup/docker-volumes
    restore_timestamp: "20250808_143055"    # Backup folder timestamp
    volume_name: "myvolume"                  # Docker volume to restore
    backup_dir: "{{ backup_base_dir }}/{{ restore_timestamp }}"
    backup_file: "{{ backup_dir }}/backup_{{ volume_name }}.tar.gz"

  tasks:
    - name: Check if backup file exists
      ansible.builtin.stat:
        path: "{{ backup_file }}"
      register: backup_file_stat

    - name: Fail if backup file does not exist
      ansible.builtin.fail:
        msg: "Backup file {{ backup_file }} does not exist!"
      when: not backup_file_stat.stat.exists

    - name: Create Docker volume if it does not exist
      ansible.builtin.command:
        cmd: docker volume create "{{ volume_name }}"
      changed_when: false

    - name: Restore the Docker volume from backup
      ansible.builtin.shell: |
        docker run --rm \
          -v {{ volume_name }}:/volume \
          -v {{ backup_dir }}:/backup \
          alpine \
          sh -c "cd /volume && tar xzf /backup/backup_{{ volume_name }}.tar.gz"
      changed_when: true
