---
- name: Create /etc/profile.d/custom_prompt.sh from template
  template:
    src: custom_prompt.sh.j2
    dest: /etc/profile.d/custom_prompt.sh
    owner: root
    group: root
    mode: '0755'

- name: Ensure script is executable
  file:
    path: /etc/profile.d/custom_prompt.sh
    mode: '0755'
