---
- name: Run backup role
  hosts: localhost
  become: true

  vars:
    src_dir: /home/srcadm/apps
    backup_dir: /opt/homelab/backup

  roles:
    - role: backup_docker_apps_directory
      vars:
        backup_docker_apps_directory_src_dir: "{{ src_dir }}"
        backup_docker_apps_directory_backup_dir: "{{ backup_dir }}"
